### PR TITLE
Add hreflang metatag to support multiple language indexing

### PR DESCRIPTION
**Pull request by drbyte**
Ref: https://moz.com/learn/seo/hreflang-tag
Ref: https://sites.google.com/site/webmasterhelpforum/en/faq-internationalisation

Credits: @balihr

### CODE REVIEW

**Comment by zcwilt** [comment]
:+1:

**Comment by ajeh** [comment]
:+1:

**Comment by torvista** [comment]
I think this implementation requires a change as documented here
https://www.zen-cart.com/showthread.php?214746-Implementing-hreflang-in-a-multilanguage-store&p=1319742#post1319742

and optionally here
https://www.zen-cart.com/showthread.php?184548-Ceon-URI-Mapping-v4-x&p=1319744#post1319744

**Comment by drbyte** [comment]
Do I correctly follow that your recommendation is this? 

```diff
  // BOF hreflang for multilingual sites
  if (!isset($lng) || (isset($lng) && !is_object($lng))) {
    $lng = new language;
  }
  reset($lng->catalog_languages);
  while (list($key, $value) = each($lng->catalog_languages)) {
-    if ($value['id'] == $_SESSION['languages_id']) continue;
+    // if ($value['id'] == $_SESSION['languages_id']) continue;
-    echo '<link rel="alternate" href="' . ($this_is_home_page ? zen_href_link(FILENAME_DEFAULT, 'language=' . $key, $request_type) : $canonicalLink . '&amp;language=' . $key) . '" hreflang="' . $key . '" />' . "\n";
+    echo '<link rel="alternate" href="' . ($this_is_home_page ? zen_href_link(FILENAME_DEFAULT, 'language=' . $key, $request_type) : $canonicalLink .  (strpos($canonicalLink, '?') ? '&amp;' : '?') . 'language=' . $key) . '" hreflang="' . $key . '" />' . "\n";
  }
  // EOF hreflang for multilingual sites
```

**Comment by torvista** [comment]
Yes.
I wasn't sure how best to skin that separator cat.

**Comment by drbyte** [comment]
I'm having trouble finding a definitive answer on whether to output the "alternate" link when a store has only one language. It seems a bit redundant when there are already other language indicators in the header.

**Pull request merged**
