### PR TITLE
Bill Smith has id 1

### PR DESCRIPTION
**Pull request by Zen4All**
In the demo data Customer Bill Smith has id 1
The reviews table has customers_id set to 0 instead of 1

[Review on Reviewable](https://reviewable.io/reviews/zencart/zc-v1-series/792)

### CODE REVIEW

**Comment by Zen4All** [comment]
not sure if I also should update mysql_upgrade_zencart_155.sql

**Comment by drbyte** [comment]
No, it's not a relevant upgrade issue.

**Comment by Zen4All** [comment]
thx, thought so

**Comment by zcwilt** [comment]
:+1:

**Pull request merged**
