### PR TITLE
Mc12345678 issue #60

### PR DESCRIPTION
**Pull request by mc12345678**
Based on initial reading, the below was added/modified to address adding notifiers to the associated auto-actions related to specials, featured purchases, and salemaker items.

In parallel: 
1. removed the closing ?>
2. converted while (!$var->EOF) statements to foreach, and
3. added bindVars references for the date.

### CODE REVIEW

**Comment by drbyte** [comment]
:+1:

**Comment by zcwilt** [comment]
In a number of places where you have converted to the iterator you still reference the ->fields array

e.g. 

     foreach ($featured as $featured_item $featured_item) {
       zen_set_featured_status($featured->fields['featured_id'], '0');
       zen_set_featured_status($featured_item->fields['featured_id'], '0');
       $zco_notifier->notify('NOTIFY_EXPIRE_FEATURED', $featured_item->fields);
}

should be referencing as an array

e.g 

    zen_set_featured_status($featured['featured_id'], '0');

**Comment by mc12345678** [comment]
*head down in shame* :) Yes, I did... Still adjusting to the new format/method. Corrected though.

**Comment by drbyte** [comment]
Oops. Ya, I saw that and overlooked it. It would have still worked, but fully implementing the iterator is definitely a better approach overall.
:+1:

**Comment by zcwilt** [comment]
:+1:

**Pull request merged**
