### PR TITLE
Fixes error created in #287

### PR DESCRIPTION
**Pull request by drbyte**
Fixes SQL error introduced in #287 

Credits to @ajeh

### CODE REVIEW

**Comment by lhungil** [comment]
:+1:

**Comment by ajeh** [comment]
This appears to fix the issue of no totals for the Products listed.

**Comment by ajeh** [comment]
:+1:

**Comment by ajeh** [comment]
:+1: 
This current fix appears to have the counts right.

**Comment by zcwilt** [comment]
:+1:

**Pull request merged**
