### PR TITLE
Add checkout_shipping reset cost

### PR DESCRIPTION
**Pull request by ajeh**
Missing reset shipping cost
https://www.zen-cart.com/showthread.php?217864-Free-Shipping-can-unintentionally-retain-cost-gt-0-if-cart-contents-change

### CODE REVIEW

**Comment by drbyte** [comment]
:+1:

**Comment by drbyte** [comment]
Granted, I like my solution better :)
https://www.zen-cart.com/showthread.php?215820-1-5-3-and-1-5-4-removal-of-shipped-product-with-free-shipping-item-remaining&p=1269364#post1269364

**Comment by scottcwilson** [comment]
Best of both worlds! :+1:

**Comment by scottcwilson** [comment]
I will add this to the 1.5.4 bug list tonight (unless someone beats me to it).

**Comment by drbyte** [comment]
I thought it had already. But it wasn't. So I posted it.

**Comment by drbyte** [comment]
:+1:

**Comment by zcwilt** [comment]
:+1:

**Pull request merged**
