### PR TITLE
add missing fontawesome-webfont.woff2 and allow in .htaccess

### PR DESCRIPTION
**Pull request by bislewl**

### CODE REVIEW

**Comment by drbyte** [comment]
Could you do a quick test to confirm whether all those .htaccess files need to be touched. I suspect only the one in the templates folder needs touching, as there are no font files outside of that folder.

**Comment by bislewl** [comment]
@drbyte you are correct

**Comment by drbyte** [comment]
:+1:

**Comment by zcwilt** [comment]
:+1:

**Pull request merged**
