### PR TITLE
fix issue of: Illegal string offset 'id' in classes/order.php

### PR DESCRIPTION
**Pull request by bislewl**
Fix issue of
PHP Warning:  Illegal string offset 'id' in /public_html/dev/includes/classes/order.php

### CODE REVIEW

**Comment by drbyte** [comment]
Thanks for the PR.  What specific steps will trigger the problem? (The last time I saw this it was caused by an outdated shipping module or other changes to core files.)

**Comment by bislewl** [comment]
It seemed to have been created from when displaying the estimated shipping on shopping_cart and having the store tax set to the shipping zone. Using isset() seemed to be a simple solution and it resolved the issue. It's incredibly possible you are correct (and I suspect you are), would it cause any harm, or would it provide some backward functionality?

**Comment by drbyte** [comment]
Not likely to cause any harm at all. Just wanting to be sure to understand the scope in case there's actually a broader compatibility fix that might be even more beneficial.

**Comment by drbyte** [comment]
:+1:  I'm okay with this. 

However, a review of code suggests there are additional places where a similar test is warranted. ie: search for `$_SESSION['shipping']['id']` and there are various places where it references the id or cost elements without first testing for their existence or where they're not confirmed or set in preceding code.

This was an ugly architecture problem inherited from osC years ago, which didn't surface until strict array handling happened in PHP 5.4. Clearly there's still more that could be done to clean it up better.

**Comment by zcwilt** [comment]
:+1:

**Comment by ajeh** [comment]
:+1:

**Pull request merged**
