### PR TITLE
change category_tree to __construct

### PR DESCRIPTION
**Pull request by Zen4All**
according to php7

---
This change is [Reviewable](https://reviewable.io/reviews/zencart/zc-v1-series/899)

### CODE REVIEW

**Comment by Zen4All** [comment]
Sorry, this is wrong. Closing the pull

**Comment by drbyte** [comment]
Right - changing to `__construct` here would have been wrong. 

The change in PHP7 is not to force having a __construct method, but rather that the treatment of a "method named the same as the class" will no longer be automatically considered to be an alias of __construct ... ie: if you want a __construct method, you must be explicit.  
In the case of this class, an explicit constructor isn't necessary.

**Comment by Zen4All** [comment]
Yes, i noticed the mistake after submitting. Early morning coding, and lack of caffeine.

**Comment by drbyte** [comment]
Ha! That reminds me: time for coffee!

**Pull request closed without merging**
