### PR TITLE
Remove block of dead code

### PR DESCRIPTION
**Pull request by scottcwilson**

### CODE REVIEW

**Comment by drbyte** [comment]
I'm a bit reluctant to remove this, as it was left commented to show a different query for a different strategy on determining the data being retrieved.

Have you looked into its history to confirm that the old will never be wanted again?

**Comment by scottcwilson** [comment]
This giant commented out block of code has been in there, commented out, since Zen Cart 1.3.6.   We have source control.  Why not clean it out and introduce it again only if it is actually needed?

**Comment by drbyte** [comment]
Thanks for checking the history.

👍

**Comment by zcwilt** [comment]
:+1:

**Comment by ajeh** [comment]
:+1:

**Pull request merged**
