### PR TITLE
Implement intermediate "shared" template tier

### PR DESCRIPTION
**Pull request by scottcwilson**
Provides for "shared" directory which is searched after your_template but before template_default.

Tested with the following files: 
includes/languages/english/html_includes/shared/define_main_page.php
includes/languages/english/shared/index.php
includes/languages/shared/english.php
includes/languages/english/shared/header.php
includes/templates/shared/common/tpl_header.php
includes/templates/shared/templates/tpl_login_default.php
- also tested with editing the first file in the admin defines pages editor.

### CODE REVIEW

**Comment by scottcwilson** [comment]
The order of inclusion in includes/languages/english.php is shared first, then template or default.  I just realized this.  I want to get some feedback before I make more changes though since people might prefer this order.

**Comment by drbyte** [comment]
Okay :+1:

**Comment by zcwilt** [comment]
:+1:

**Comment by ajeh** [comment]
:+1:

**Comment by drbyte** [comment]
Closes #340

**Comment by Zen4All** [comment]
When testing this brilliant new feature, I stumbled across a possible bug.
I created a new css folder in the shared template folder and a new (empty) css file called stylesheet_test.css. After this I reloaded my test zc 1.6 site and all the formatting is gone, because zc now only looks in the shared/css folder for all the style sheets. The same is happening when putting a single image in the shared/images/icons directory

**Comment by scottcwilson** [comment]
Do people agree that the comment above by @Zen4All is in fact an issue?  Putting a blank stylesheet in your current template would have the same effect.

**Comment by drbyte** [comment]
The behavior until v1.5.x has always been that any stylesheet or javascript file being present in the override folder would cause the override folder to be the only folder used for css or js.  For images it would still cascade up to template_default.

**Comment by Zen4All** [comment]
May be I misunderstood the function of the "shared" folder, but let me explain what I thought I could do with it.
I have build a new multi store module, but I think it would also work on the current multi site module.
And have ported the shared folder functionality to Zen Cart 1.5.4
Each store has its own unique template folder so the structure would look like this:
```
includes
 |- templates
   |- classic
   |- shared
   |- store1
   |- store2
   |- store3
   |- store4
   |- template_default
```
To reduce the number of files I wanted to put all "shared" files between the different store templates in the shared folder. Like said in the other post this works for the template folder, but not the css, jscript, and images.

**Comment by drbyte** [comment]
Understood. 

What you described should work fine for images (er, well, it always has before the `shared` folder was introduced).

But ... 

Question: do you want it to automatically load *ALL* the stylesheets for `store1` AND `shared` AND `template_default`? Wouldn't that potentially result in some undesired results?  And wouldn't that therefore cause extreme temptation to alter the `template_default` files?

Same with javascript files.

**Comment by Zen4All** [comment]
I have been rethinking this problem, and it came to the conclusion the **functionality should stay as it is** right now. Sharing Image/css/jscript folders will create a whole bunch of new problems, which is not worth the effort.

**Comment by scottcwilson** [comment]
Should this issue be closed?

**Comment by drbyte** [comment]
@Zen4All thanks for posting back after having researched further. 

I'm glad that you didn't just "accept" the offered response, but instead took the time to challenge it, even though you decided it should stay as-is.  I don't mind being wrong ... in fact I'd rather know that there's a problem or "use case" that hasn't been considered yet, so that we can collectively come up with an even better solution. That's the value of community and open source!

Thanks again for contributing!

**Pull request merged**
