### PR TITLE
Query can be simpliefied

### PR DESCRIPTION
**Pull request by Zen4All**
The info in this query is already present in $reviews.

[Review on Reviewable](https://reviewable.io/reviews/zencart/zc-v1-series/650)

### CODE REVIEW

**Comment by drbyte** [comment]
Good catch.

In fact, if we simply add this to the `$reviews_query_raw` on line 257, this query you're mentioning can most likely be removed altogether.

`, length(rd.reviews_text) as reviews_text_size`

**Comment by Zen4All** [comment]
The file has been updated

**Comment by zcwilt** [comment]
:+1:

**Comment by drbyte** [comment]
:+1:

**Pull request merged**
