### PR TITLE
Replace deprecated HTML

### PR DESCRIPTION
**Pull request by DivaVocals**
*language="javascript"* is deprecated as the "language" value is an identifier which has no standards.

*type="text/javascript"* is the correct syntax.

### CODE REVIEW

**Comment by DivaVocals** [comment]
Not sure if I've done something wrong here, but the ONLY thing I wanted to commit to this PR was the *type="text/javascript"* changes.. Hopefully that's ALL that is REALLY in this PR.. The rest of the commits to my fork were to synch my fork up with the latest changes to the master ZC repo..

**Comment by drbyte** [comment]
Ya, normally the best-practice is to always create a new branch for any PR you want to make.  That way you can do periodic merges to keep your main branch (ie: v160) up to date, and then anytime you want to do a PR, you make a new branch off v160 and do your changes there, then do the PR from that feature-branch.

**Comment by texdc** [comment]
:+1: nice changes!

**Comment by DivaVocals** [comment]
@texdc HA! thanks small potatoes compared to what you guys are doing..
@drbyte Gotcha.. Guess I'm so used to flying "solo" with my own Github repos, that I forget that I need a different flow to play nicely with others.. Going forward, I'll do as you suggest.. Might have some time on my hands for the next week or so to finally get back to playing with v1.6. A "little birdie" made a suggestion on how to improve my changes.. So I'm gonna take a looksee at the suggestion and submit the change accordingly..

**Comment by drbyte** [comment]
One of the benefits of using separate feature-branches is that any subsequent pushes you do to those branches (in your own repo) get automatically included in any open PR for that same branch ... so it's easy to add commits to an open PR if you're asked (or need) to tweak something.

**Comment by DivaVocals** [comment]
@drbyte - Got it.. I'll try not to color outside the lines going forward.. :laughing: 

That said, do you guys wanna just reject my pull request, and let me have a big old DO-OVER so I can start off on a better footing?? :smiley_cat:

**Comment by drbyte** [comment]
If you're gonna do more with it anyway then sure. You can probably close it yourself too.

**Comment by DivaVocals** [comment]
Okay cool.. let me close this and start over

**Pull request closed without merging**
