### PR TITLE
Fixes crash on initial db update for new admin user in no SSL environment

### PR DESCRIPTION
**Pull request by scottcwilson**
Initializes some db fields on the screen from configure.php.

### CODE REVIEW

**Comment by drbyte** [comment]
> Fixes crash on initial db update

Was that with a specific MySQL "mode" enabled (maybe the strict dates in MySQL 5.7)? Which version of MySQL, on what O/S? What was the error message?

**Comment by scottcwilson** [comment]
[25-Feb-2015 14:13:39 America/New_York] PHP Fatal error:  1292:Incorrect
datetime value: '0' for column 'pwd_last_change_date' at row 1 :: update
admin set admin_name = 'help', admin_email = 'help@thatsoftwareguy.com',
admin_pass = '79afb42ab1c14dddc09242acb711d012:c9', pwd_last_change_date =
0, reset_token = '1425150819}cc4642fca3f5be4f971e9ac19d2ea6cd:7d' where
admin_id = 1 ==> (as called by)
/Users/scott/Sites/demo_160/zc_install/includes/classes/class.zcDatabaseInstaller.php
on line 400 <== in
/Users/scott/Sites/demo_160/includes/classes/db/mysql/query_factory.php on
line 165

MAMP running on OSX (Yosemite) using MySQL 5.5.38.

**Comment by drbyte** [comment]
:+1:

**Comment by ajeh** [comment]
:+1:

**Comment by drbyte** [comment]
In future, please keep separate features as separate branches and separate PRs.

**Comment by scottcwilson** [comment]
oh ok sorry - I was intending to only do the install tweak but then it
crashed so I went ahead and fixed that too.

**Pull request merged**
