### PR TITLE
Fix UTF8 sequence error in ajax call

### PR DESCRIPTION
**Pull request by drbyte**
Ref: https://www.zen-cart.com/showthread.php?216691-PHP-Warning-Invalid-UTF-8-sequence-in-argument-in-ajax-php-on-line-24

### CODE REVIEW

**Comment by drbyte** [comment]
Note: Uncertain whether this is entirely the correct fix. If it's really more specific to the PayPal module, then it might be worth making some additional/adjustments there.

**Comment by zcwilt** [comment]
:+1:
I've no problem with this fix for now.

**Comment by ajeh** [comment]
:+1:

**Comment by drbyte** [comment]
Just posting to link to the alternate fix posted by @lat9 at https://www.zen-cart.com/showthread.php?21669124&p=1294488#post1294488

**Comment by drbyte** [comment]
@zcwilt made a PR #613 to address this

**Pull request merged**
