### PR TITLE
Correctly check admin module 'key' counts

### PR DESCRIPTION
**Pull request by scottcwilson**
Fixes admin/modules.php so that module key counts are correctly checked.  This check was skipped because the if statement was incorrect.

### CODE REVIEW

**Comment by scottcwilson** [comment]
Testing procedure: correctly configure payment module Money Order; observe no errors.  In mysql, run

delete from configuration where configuration_key = 'MODULE_PAYMENT_MONEYORDER_SORT_ORDER';

Refresh admin->modules->payment; still no error is observed.  Fix file admin/modules.php; see error message.  Fix configuration; observe no errors.

**Comment by scottcwilson** [comment]
Updated at Linda's recommendation.  Additional tests:
- test when Money Order installed by set to false.
- test after adding an additional key to money order (upgrade scenario).

**Comment by drbyte** [comment]
:+1:

**Comment by ajeh** [comment]
:+1:

**Pull request merged**
