### PR TITLE
Styling improvements for "Setup Wizard" dialog

### LINKED ISSUE #611: Admin - Styling improvements for "Setup Wizard" dialog
TWO WAYS TO GET TO THIS SCREEN:

1. Via fresh install
a) Do a fresh install.
b) Login to Admin for the first time. (Follow the password reset prompt if it occurs.)

2. A simple reset in an existing install
a) Login to Admin
b) Go to Admin->Configuration->My Store and make either the store name or store owner be blank. Then save. 

Note the setup wizard dialog, which needs some designer love.

### PR DESCRIPTION
**Pull request by barco57**
Fixes #611

### CODE REVIEW

**Comment by zcwilt** [comment]
Hi. Still testing this, but changes have broken the jquery update of zones on a country change

Fix seems to be to do 

```
        <div class="small-9 columns" id="store_zone_container">
          <?php echo $tplVars['zoneString']; ?>
        </div></label>
```

**Comment by zcwilt** [comment]
Also, the dropdown seems to be cut off a little.
Firefox 41.0.2 on Ubuntu 15.04

screenshot-zen local 2015-10-17 19-58-55

**Comment by drbyte** [comment]
I'm guessing that a change similar to https://github.com/zencart/zc-v1-series/pull/612 might fix that cut off text in the dropdown.

**Comment by jtwebsitedesign** [comment]
Are these changes pulled into the main repo so I can fork it?

**Comment by drbyte** [comment]
Merged to allow @jtwebsitedesign to continue work from this point.

**Pull request merged**
