### PR TITLE
Expand admin/modules

### PR DESCRIPTION
**Pull request by bislewl**
Interesting thought inspired by #483, what about if the admin/modules.php was expanded to include plugins. The install function is there, along with remove and edit values. What about:

1. This was expanded to support external plugins 
2. It became the "preferred" method for installation/removal of plugins

That  I would think would reduce the need for all this custom code for auto-installers additionally the version number could be stored there as well so we could use the plugin_version_check_for_updates() function as part of it. And since there would be a uninstall function it should solve the need for uninstall files as well, it would also remove the need for the sometimes the 30-40 item in the configuration menu, since it could use the framework already set up. And it would allow for the ability to modify multiple configuration values at a single time. It seems like it was almost originally intended for this...

### CODE REVIEW

**Comment by drbyte** [comment]
Do you have a plugin in mind to use as an example of how it would fit into this sort of structure?  Perhaps another github repo we can dialog about or collaborate in?

**Comment by bislewl** [comment]
Sure, I haven't written one for this structure yet. 

I branched Ajax Back in Stock https://www.zen-cart.com/downloads.php?do=file&id=1944  https://github.com/bislewl/ajax_back_in_stock/tree/proposed_160_plugin_structure and added @drbyte  @zcwilt and @ajeh . Do you agree with the general premise?

**Comment by drbyte** [comment]
> Do you agree with the general premise?

We're still discussing it. Willing to explore it before fully committing to it.

**Comment by drbyte** [comment]
@bislewl ... I think it's best to close this PR for the time being. 

We're working on a project to refactor a bunch of things in the Admin, so the code landscape is going to change a bit, and it may be worth revisiting these thoughts after that's done.

Thoughts?

**Comment by bislewl** [comment]
I agree

**Pull request closed without merging**
