### PR TITLE
Remove dead

### PR DESCRIPTION
**Pull request by scottcwilson**

### CODE REVIEW

**Comment by drbyte** [comment]
Can you revert the 2nd commit there, and then re-push the branch? The shipping.php and ot-coupon stuff are being fixed as part of the merge from v155.

Something like:
1. change to this branch on your local
2. reverse the commit: `git reset --hard 9f47784`
3. then `git push --force`

Basically, your first commit is fine, but the second one is both conflicting with recent merges and I think it's already taken care of in what has been merged.

**Comment by scottcwilson** [comment]
done

**Comment by drbyte** [comment]
There's still a merge conflict ... and it appears to be in another file which you haven't included in this PR:  `/includes/library/zencart/Services/src/IndexRoute.php` ... probably because it's part of submodules.

```php
      public function doWidgetsDisplay()
      {
 -        $widgetProfileList = WidgetManager::getInstallableWidgetsList($_SESSION ['admin_id'], $_SESSION ['languages_id']);
          $widgetInfoList = WidgetManager::getWidgetInfoForUser($_SESSION ['admin_id'], $_SESSION ['languages_id']);
++<<<<<<< HEAD:includes/library/zencart/Services/src/IndexRoute.php
 +        $widgetList = widgetManager::loadWidgetClasses($widgetInfoList);
 +        $this->listener->setTplVar('widgetList', $widgetList);
 +        $this->listener->setTplVar('widgets', WidgetManager::prepareTemplateVariables($widgetList));
 +        $this->listener->setTplVar('widgetInfoList', $widgetInfoList);
++=======
+         if ($widgetInfoList) {
+            $this->templateVariables ['widgetList'] = WidgetManager::loadWidgetClasses($widgetInfoList);
+         } else {
+            $this->templateVariables ['widgetList'] = array();
+         }
+         $this->templateVariables ['widgets'] = WidgetManager::prepareTemplateVariables($this->templateVariables ['widgetList']);
+         $this->templateVariables ['widgetInfoList'] = $widgetInfoList;
++>>>>>>> 9f4778435250384ac413df12963c0202540f66cf:admin/includes/classes/actions/admin/class.zcActionAdminIndex.php
      }
```

Are your changes to that file necessary too? Or is the "solution" a "one or the other, but not both" scenario?

**Comment by scottcwilson** [comment]
I have no idea what happened - it seems the file I wanted to change (admin/includes/classes/actions/admin/class.zcActionAdminIndex.php) does not exist anymore.

**Comment by drbyte** [comment]
Okay, I see. I think what's happened is that file was moved and also has had some updates. It's now in `/includes/library/zencart/Services/src/IndexRoute.php`

**Comment by scottcwilson** [comment]
Was something equivalent to my update included?  If not, I think it will error on a fresh 1.6.0 database. I can re-test this weekend if needed - just can't do it right now.

**Comment by drbyte** [comment]
No, I think the bug you were aiming to fix probably still exists.

**Comment by scottcwilson** [comment]
ok.  Please let me know when all merges are complete and I will try again.

**Comment by drbyte** [comment]
merges affecting that part of the code are complete

**Comment by scottcwilson** [comment]
I have tried a few times to dup and it seems  solid.  Even an old bug Linda
reported has been fixed.

**Pull request closed without merging**
