### PR TITLE
Style Changes for the Admin Widgets

### LINKED ISSUE #604: Admin Widget Styling (overall admin look and feel)
I have been playing with the widget styling, they needed some love, but I am wondering what the "Vision" is for the admin look and feel? Has there been any conversation about it?
Below is something I came up with for the widget styling that is pretty neutral.
admin_index_widget_styling

### PR DESCRIPTION
**Pull request by barco57**
Fixes #604

### CODE REVIEW

**Comment by drbyte** [comment]
Home page looks good. 

But still some work to be done to isolate it to just the home page and not negatively affect the other pages.  I think @ajeh will have some feedback about the products and price manager pages, customers, etc.

It's a great start. :+1:  To make additional changes, commit them locally and push the commit back to github, and they'll show up here as part of this pull request.

**Comment by ajeh** [comment]
While I like the Widgets, I am not too keen on the rest of the Admin as everything is rather wonky looking.

Category/Products section where text is bold or bigger but input boxes are tiny, for example.
Tiny menu bar.

It's a great start, but the other affects through the rest of the Admin need to be considered that these changes result in.

**Comment by drbyte** [comment]
I do like that better ;)

**Comment by ajeh** [comment]
Much better second time around.

**Comment by drbyte** [comment]
It appears that @zcwilt likes it too!

**Comment by zcwilt** [comment]
oops

**Pull request merged**
